version: '3.8'

services:
  turtle-identifier:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - UPLOAD_FOLDER=uploads
      - MAX_CONTENT_LENGTH=16777216
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
